// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.9.10'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.10"
        // Firebase services plugin classpath. Required to apply Firebase services such as
        // Cloud Messaging in the app module. Without this, the Google services plugin will
        // not be recognized by the Gradle build.
        classpath 'com.google.gms:google-services:4.4.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// NOTE: Do not place your application dependencies here; they belong
// in the individual module build.gradle files